# Generated by Django 6.0.6 on 2026-06-16 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_userprofile_education_workexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address_line',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='agency_employee_no',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='barangay',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='citizenship',
            field=models.CharField(default='Filipino', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city_municipality',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='num_children',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='province',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='status_of_appointment',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
        migrations.CreateModel(
            name='CivilServiceEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_service', models.CharField(max_length=100)),
                ('license_number', models.CharField(default='N/A', max_length=50)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibilities', to='blog.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('dates', models.CharField(max_length=50)),
                ('hours', models.IntegerField(default=0)),
                ('conducted_by', models.CharField(max_length=200)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='blog.userprofile')),
            ],
        ),
    ]
