# Generated by Django 6.0.6 on 2026-06-16 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_userprofile_address_line_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address_line',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='barangay',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='city_municipality',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='num_children',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='province',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='inclusive_dates',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='status_of_appointment',
        ),
        migrations.AddField(
            model_name='education',
            name='year_graduated',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='blood_type',
            field=models.CharField(choices=[('N/A', 'N/A'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='N/A', max_length=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_relationship',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='height',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='per_barangay',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='per_city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='per_house_no',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='per_province',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='per_street',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='per_subdivision',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='per_zip',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='res_barangay',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='res_city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='res_house_no',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='res_province',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='res_street',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='res_subdivision',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='res_zip',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='same_as_residential',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telephone',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weight',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='currently_working',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='education',
            name='level',
            field=models.CharField(choices=[('Elementary', 'Elementary'), ('Secondary', 'Secondary'), ('College', 'College'), ('Vocational', 'Vocational')], max_length=50),
        ),
        migrations.AlterField(
            model_name='education',
            name='school_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='citizenship',
            field=models.CharField(choices=[('Filipino', 'Filipino'), ('Dual Citizen', 'Dual Citizen'), ('Other', 'Other')], default='Filipino', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='civil_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Separated', 'Separated')], default='Single', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name_extension',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='company',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='position',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='blog.userprofile')),
            ],
        ),
    ]
