# Generated by Django 6.0.6 on 2026-06-18 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_userprofile_address_line_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDataSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_code', models.CharField(blank=True, max_length=10)),
                ('province_name', models.CharField(blank=True, max_length=100)),
                ('municipality_code', models.CharField(blank=True, max_length=10)),
                ('municipality_name', models.CharField(blank=True, max_length=100)),
                ('barangay_code', models.CharField(blank=True, max_length=10)),
                ('barangay_name', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=4)),
            ],
        ),
    ]
