name: Deploy Django Updates automatically

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # 👇 MAKE SURE THIS STEP IS PRESENT AND AT THE VERY TOP
      - name: Pull latest code from GitHub
        uses: actions/checkout@v4

      - name: Install dependencies and run migrations
        run: |
          source ~/projects/OJT_PITO/venv/bin/activate
          pip install -r requirements.txt
          python manage.py migrate --noinput
          python manage.py collectstatic --noinput

      - name: Restart Services
        run: |
          sudo service nginx restart
